version: '3'
services:
  parrot:
    image: dekokun/parrot
  proxy:
    image: 'nginx:1.15.7'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - parrot
    ports:
      - '80:80'

